"""make_safety_score_nullable

Revision ID: 22d4b856090a
Revises: 315e3673667a
Create Date: 2026-06-04 23:51:27.722731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d4b856090a'
down_revision: Union[str, None] = '315e3673667a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('safety_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('safety_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
