"""add full_name and new skin types

Revision ID: 40b287f21648
Revises: 22d4b856090a
Create Date: 2026-06-05 22:43:30.790445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b287f21648'
down_revision: Union[str, None] = '22d4b856090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dry_skin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('oily_skin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('combination_skin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('normal_skin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('normal_skin')
        batch_op.drop_column('combination_skin')
        batch_op.drop_column('oily_skin')
        batch_op.drop_column('dry_skin')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
