"""initial schema

Revision ID: 996383a461cd
Revises: 
Create Date: 2026-06-14 14:08:20.253748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# EmbeddingType resolves to pgvector's Vector(384) on Postgres and LargeBinary
# on SQLite, exactly matching what the application models expect at runtime.
from app.models import EmbeddingType


# revision identifiers, used by Alembic.
revision: str = '996383a461cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # On Postgres the aliases.embedding column uses the pgvector `vector` type,
    # so the extension must exist before the table is created. No-op on SQLite.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inci_name', sa.String(), nullable=False),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('cas', sa.String(), nullable=True),
    sa.Column('regulatory_status', sa.String(), nullable=True),
    sa.Column('comedogenic', sa.Integer(), nullable=True),
    sa.Column('fungal_acne_safe', sa.String(), nullable=True),
    sa.Column('pregnancy_safe', sa.String(), nullable=True),
    sa.Column('irritant', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_inci_name'), ['inci_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('pregnant', sa.Boolean(), nullable=True),
    sa.Column('sensitive_skin', sa.Boolean(), nullable=True),
    sa.Column('acne_prone', sa.Boolean(), nullable=True),
    sa.Column('fungal_acne', sa.Boolean(), nullable=True),
    sa.Column('rosacea', sa.Boolean(), nullable=True),
    sa.Column('dry_skin', sa.Boolean(), nullable=True),
    sa.Column('oily_skin', sa.Boolean(), nullable=True),
    sa.Column('combination_skin', sa.Boolean(), nullable=True),
    sa.Column('normal_skin', sa.Boolean(), nullable=True),
    sa.Column('avoid_list', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('embedding', EmbeddingType, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_alias_name')
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_name'), ['name'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('coverage_percent', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))

    op.drop_table('scans')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_name'))

    op.drop_table('aliases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_inci_name'))

    op.drop_table('ingredients')
    # ### end Alembic commands ###
